title: UWAL
author: Ustym Ukhman
username: UstymUkhman
github_username: UstymUkhman
email: ustym.ukhman@gmail.com
linkedin_username: ustymukhman

url: https://ustymukhman.github.io
description: 🎨 Unopinionated WebGPU Abstraction Library 📚
github_link: https://github.com/UstymUkhman/uwal
remote_theme: pages-themes/minimal@v0.2.0
favicon: assets/favicon.svg
logo: assets/favicon.svg
show_downloads: true
plugins:
  - jekyll-remote-theme
