name:  Close Pull Request

on:
  pull_request_target:
    types: [opened]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: superbrothers/close-pull-request@v3
        name: Close Pull Request
        with:
          comment: "Pull requests are not accepted. If you have any questions, please feel free to file an issue."
